### ISSUE TITLE
nil pointer dereference panic

### ISSUE THREAD

**Issue by julienschmidt** [ryanrolds/sqlclosecheck#3]
Version: 115268b

When I attempt to run sqlclosecheck  on github.com/go-sql-driver/mysql, I get the following crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1214f46]

goroutine 12 [running]:
github.com/ryanrolds/sqlclosecheck/pkg/analyzer.getAction(0x14b7620, 0xc001da7400, 0xc0020354b0, 0x2, 0x2, 0xc002038a60, 0xc001da1e10)
	[...]/sqlclosecheck/pkg/analyzer/analyzer.go:207 +0x4b6
github.com/ryanrolds/sqlclosecheck/pkg/analyzer.checkClosed(0xc001dba5c8, 0xc0020354b0, 0x2, 0x2, 0x2)
	[...]/sqlclosecheck/pkg/analyzer/analyzer.go:169 +0x88
github.com/ryanrolds/sqlclosecheck/pkg/analyzer.run(0xc001d4fb00, 0x7612e97, 0x17247c0, 0xc001fc2798, 0x0)
	[...]/sqlclosecheck/pkg/analyzer/analyzer.go:61 +0x216
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	[...]/pkg/mod/golang.org/x/tools@v0.0.0-20200625211823-6506e20df31f/go/analysis/unitchecker/unitchecker.go:350 +0x6d8
sync.(*Once).doSlow(0xc001ce19f0, 0xc0004ef728)
	/usr/local/Cellar/go/1.14.5/libexec/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.14.5/libexec/src/sync/once.go:57
golang.org/x/tools/go/analysis/unitchecker.run.func5(0xc00011b450, 0x0)
	[...]/pkg/mod/golang.org/x/tools@v0.0.0-20200625211823-6506e20df31f/go/analysis/unitchecker/unitchecker.go:303 +0x1b3
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0xc0004f9958, 0xc000ebe6b0, 0xc00011b450)
	[...]/pkg/mod/golang.org/x/tools@v0.0.0-20200625211823-6506e20df31f/go/analysis/unitchecker/unitchecker.go:362 +0x33
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
	[...]/pkg/mod/golang.org/x/tools@v0.0.0-20200625211823-6506e20df31f/go/analysis/unitchecker/unitchecker.go:361 +0xa3
```

**Comment by ryanrolds** [comment]
Thank you for reporting this and your PRs. I make sure they are reviewed by end-of-day tomorrow.

**Comment by ryanrolds** [comment]
I'm going to look at a line number issue I noticed. After I investigate that I will tag and get `golangci-lint` updated.
